name: Production testing & deployment

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - "vite/**"
      - "tree/**"
      - "firestore-serializers/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install lib package
        run: cd firestore-serializers && yarn
      - name: Build lib package
        run: cd firestore-serializers && yarn build
      - name: Install lib tree
        run: cd tree && yarn
      - name: Build lib tree
        run: cd tree && yarn run compile
      - name: Install Vite package
        run: cd vite && yarn
      - name: Build Vite
        run: cd vite && yarn run build
      - name: Install Server package
        run: cd server && yarn && yarn global add @todesktop/cli
      - name: Send to ToDesktop
        working-directory: ./server
        run: yarn run copy-fe && todesktop build && todesktop release --latest --force
        with:
          - TODESKTOP_ACCESS_TOKEN: ${{ secrets.TODESKTOP_ACCESS_TOKEN }}
          - TODESKTOP_EMAIL: ${{ secrets.TODESKTOP_EMAIL }}
